### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Craftsman96** [HappyBavarian07/Admin-Panel#3]
Hey wollte Mal fragen ob du für nen ebenfalls Bayern Mal 10 Minuten oder so für ein Gespräch hättest. Zum einen wegen ein paar Ideen fürs Admin Panel und noch wegen einer anderen Sachen 😅

**Comment by HappyBavarian07** [comment]
Bin gerade leider im Urlaub aber sobald ich zurück bin gerne, aber du kannst mich gerne auf Discord adden dafür! (Name steht auf SpigotMC (HappyBavarian07#0285)). Discord kann ich nämlich auch im Urlaub benutzen, nur Micro und Internet ist nicht das beste! Sobald ich daheim bin werde ich auf die Sache zurückkommen!
